[versions]
spring-boot = "4.1.1"
openapi-generator = "7.25.0"
junit = "5.13.4"
assertj = "3.27.6"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
